language: c

env:
  - ARCH=arm64
  - ARCH=armhf

addons:
  apt:
    packages:
    - linux-base
    - fakeroot
    - debhelper
    - devscripts
    - lintian
    - build-essential
    - devio

git:
  depth: 1

install:

script:
  - dpkg-buildpackage -a${ARCH} -d -uc -us

before_deploy:
  - export RELEASE_PACKAGES=$(ls ../*.deb)
  - git config --global user.email "tobetter@gmail.com"
  - git config --global user.name "Dongjin Kim"
  - export GIT_TAG=travis/${TARGET_BOARD}-${TRAVIS_BUILD_NUMBER}
  - git tag ${GIT_TAG} -a -m "Tagged by Travis (${TRAVIS_BUILD_NUMBER})"
  - git push --quiet https://tobetter:${PRIVATE_ACCESS_TOKEN}@github.com/tobetter/flash-kernel ${GIT_TAG}

deploy:
  provider: releases
  api_key:
    secure: ${PRIVATE_ACCESS_TOKEN}
  file_glob: true
  file: ../*.deb
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
